remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme

minima:
  skin: auto
  hide_site_feed_link: true
  nav_pages:
    - README.md
    - 2025/README.md
    - 2024/README.md
    - 2023/README.md
    - 2022/README.md
    - 2021/README.md



title: Advent Of Code
description: Solutions and explanations for Advent of Code challenges

# author:
#   name: Ivan Imbert
